name: Deployment

on:
  workflow_call:
    inputs:
      env:
        description: 'Name of the environment'
        default: 'Stage'
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo "Input _${{ inputs.username }}_"
      - run: echo "vars _${{ vars.username }}_"
      - run: echo "secrets _${{ secrets.token }}_"
