name: Trigger

on:
  push:
  
  
jobs:
  TriggerProd:
    if: github.ref == 'refs/heads/main'
    uses: jan-tricks/workflows/.github/workflows/deployment.yml@main
    with:
      env: "Production"
    secrets: inherit
    
  TriggerStage:
    if: github.ref == 'refs/heads/develop'
    uses: jan-tricks/workflows/.github/workflows/deployment.yml@main
    with:
      env: "Stage"
    secrets: inherit
