name: Trigger

on:
  push:
  
  
jobs:
  pass-secret-to-workflow:
    environment: Production
    uses: ./.github/workflows/deploy.yml
    with:
      username: ${{ vars.username }}
    secrets:
      token: ${{ secrets.token }}
