name: Trigger

on:
  push:
  
  
jobs:
  TriggerProd:
    if: github.ref == 'refs/head/main'
    uses: ./.github/workflows/deploy.yml
    with:
      env: "Production"
    secrets: inherit
    
  TriggerStage:
    if: github.ref == 'refs/head/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      env: "Stage"
    secrets: inherit
