name: Trigger

on:
  push:
  
  
jobs:
  Trigger:
    name: ${{ github.ref_name }}
    uses: jan-tricks/workflows/.github/workflows/deployment.yml@main
    with:
      env: ${{ github.ref_name }}
    secrets: inherit
